### ISSUE TITLE
.toBeA('array')

### ISSUE THREAD

**Issue by rstacruz** [mjackson/expect#10]
How about it? It would be nice to have a wrapper around `expect(Array.isArray(list)).toEqual(true)` (yuck).

For reference, chai.js has `expect(list).to.be.a('array')`.

**Comment by mjackson** [comment]
You can already do `expect([]).toBeAn(Array)`.

**Comment by rstacruz** [comment]
that does `x instanceof Array` though, not `Array.isArray(x)` or equivalent.

**Comment by mjackson** [comment]
ok, let's add it
