### ISSUE TITLE
Document spy properties (calls)

### ISSUE THREAD

**Issue by davidtheclark** [mjackson/expect#100]
What would you think of adding properties to the documentation about spies? 

As I was first using this library's spies today, it wasn't immediately evident to me that there was a `calls` property that I could use to count and check individual calls — because it was just part of an example instead of being explicitly documented along with the methods.

We could change that section title to "Spy methods and properties", then add a subsection for `calls`, and document the property of the call object that `calls` lists.

I'd be happy to write up a PR for this, but wanted to run it by you first to see what you think.

**Comment by mjackson** [comment]
@davidtheclark That would be great, thank you. Overall the API docs are kind of getting long. Eventually I'd like to find a way to make browsing them a bit easier.

**Comment by davidtheclark** [comment]
Ok. I'll try to find time to put together a quick PR this weekend.
