### ISSUE TITLE
.toBeGreaterThanOrEqual()

### ISSUE THREAD

**Issue by rstacruz** [mjackson/expect#11]
It would be nice to have `>=` and `<=` assertions.

Also, this alias may be good: `.toCompare('>=', 5)` (dont know how to name it!)

**Comment by mjackson** [comment]
I think `.toBeGreaterThanOrEqualTo` is a good name. I'd be happy to accept a PR that does this.

**Comment by rstacruz** [comment]
I think `...OrEqual` is better than `...OrEqualTo` though, simply because it keeps parity with `.toEqual`, but that's just a minor nitpick on my part :)

**Comment by mjackson** [comment]
Now that we have `expect.extend` we can leave this up to a 3rd party lib, no? You still want it in core?

Actually, I'm kind of thinking we could refactor our whole library to use `extend` internally... not sure it would be worth it though.

**Comment by rstacruz** [comment]
I like the idea of using `extend()` internally, but i'm with you that it's small enough that it doesn't warrant it.

**Comment by hrj** [comment]
Would be good to have this.

:+1:
