### ISSUE TITLE
Browser tests are flaky

### ISSUE THREAD

**Issue by ljharb** [mjackson/expect#118]
Some of the browser tests seem to be failing a lot, causing a lot of false test failures.

These tests should be made reliable, or removed, as flaky tests cause more harm than good.

**Comment by ljharb** [comment]
See #117, #116, #114, #112.

**Comment by just-boris** [comment]
+1 to disable browser tests.
Probably most modern browsers follow the spec about values equality, so it doesn't need to check in every browser, it will be enough to check only exotic cases, like IE8

**Comment by ljharb** [comment]
I think the browser tests are critically important, in every version of every browser (since EVERY version of every browser is exotic and broken in some way). However, flaky tests are worse than none.

**Comment by mjackson** [comment]
Ya, agree w @ljharb here. This needs to be fixed.

The flaky piece is BrowserStack. I keep getting [timeouts](https://travis-ci.org/mjackson/expect/builds/143404918#L1221-L1222). Honestly, [the `karma-browserstack-launcher` config](https://github.com/mjackson/expect/blob/f0314f0d77fcced3560824a3f7f6b2c606d4a0ba/karma.conf.js#L93-L105) is kind of black magic to me. I just cargo cult it around to all my OSS repos. But occasionally it flakes out.

**Comment by mjackson** [comment]
BTW, Browserstack only lets us run 2 tests in parallel. It may be the case that tests are timing out because we try to fire up 8 browsers at the beginning and then others timeout.

**Comment by mjackson** [comment]
I updated our Karma config to [only run 2 browsers](https://github.com/mjackson/expect/commit/e4908ae46099dac6b94832bf02416a42127352e0#diff-a2a3b7b0c9c3b4b93b4aebf4e3ec3cfbR88) at once. Hopefully this improves the situation.
