### ISSUE TITLE
A way to restore all spies

### ISSUE THREAD

**Issue by rstacruz** [mjackson/expect#12]
It would be great if we can kill all spies in one go:

```js
afterEach(function () {
  expect.restoreAllSpies();
});
```

This would be similar to sinon.js's sandbox functionality.

**Comment by rstacruz** [comment]
would be happy to contribute code, btw — just lemme know and i'll send ya a PR :)

**Comment by mjackson** [comment]
I just cut version 1.7.0, which includes [support for restoring spies](https://github.com/mjackson/expect/commit/4318bedb2109ececea4d3e839cd0cf8297fbdc37). If you'd like to take a shot at a PR that restores all in one go, that would be great.
