### ISSUE TITLE
`expect('').toEqual([])` passes

### ISSUE THREAD

**Issue by flushentitypacket** [mjackson/expect#127]
```js
expect('').toEqual([])
```

I would expect this to fail. This is probably more of an issue in the underlying lib that governs `toEqual`, but I thought it was worth reporting as an issue here.

**Comment by ljharb** [comment]
`toEqual` is like `==` - and an empty array stringifies to the empty string. You should only be using `toEqual` when you know the possible types of the things you're comparing, and when you expect the associated implicit coercions. `toBe` is more like `===` if you want strict comparison.

**Comment by rstacruz** [comment]
Yeah, you might want deepEqual instead.

**Comment by flushentitypacket** [comment]
`===` doesn't apply in this case, either. I understand how `==` and `===` work, but it seems like a bad thing that we literally cannot craft a test for this particular case.

Perhaps the correct thing is to check both `typeof` and `==`?

**Comment by ljharb** [comment]
@flushentitypacket Of course you can. `expect(Array.isArray(foo)).toEqual(true); expect(foo).toEqual([]);`

**Comment by ljharb** [comment]
If you always make assertions on the types of things you're working with up front, you can avoid a lot of confusion later on - in tests as well as implementations.

**Comment by flushentitypacket** [comment]
Yeah, that seems like how I'll have to structure such a test going forward. Thanks!
