### ISSUE TITLE
Default messages

### ISSUE THREAD

**Issue by rstacruz** [mjackson/expect#13]
Doing this:

```js
expect(2).toEqual(3)
```

gets you this assertion error:

```
Error: 2 deepequal 3
```

Would you like expect to have better default assertion messages, like `Expected 2 to equal 3`?

**Comment by mjackson** [comment]
Yes, that would be great. We should probably just add [`deep-equal`](https://www.npmjs.com/package/deep-equal) as a dep and use that instead of using `assert.deepEqual` there.
