### ISSUE TITLE
call function via closure vs call on es6 module. How to mock?

### ISSUE THREAD

**Issue by casertap** [mjackson/expect#139]
Hi guys I created a stackoverflow issue but I think I can get a better answer in here.

http://stackoverflow.com/questions/38579934/js-call-function-via-closure-vs-call-on-es6-module?noredirect=1#comment64549051_38579934

I have 2 functions defined like this:
```
export function builder(){ ... };
export function action() { return () => builder() };
```
Now I am trying to write a test that mock the builder function and return {};
```
 import * as m from 'redux/modules/mymodule';

 it('call buildSolrUrl', () => {
  const spy = expect.spyOn(m, "builder").andReturn({});
  m.action()();
  expect(spy.calls.length).toEqual(1);
 });
```
The problem is that builder does not get mock in that case. If I change my code for:
```
export function action() { return () => this.builder() };
```
The method is mocked but my program does not work anymore because action() return a function that is executed later and ```this``` is not resolved to the right object.

To resume: My code works because the call to builder() is done via closure. The tests are unable to mock the function that way because the function is called via the closure.

What is the best way to deal with this?

**Comment by ljharb** [comment]
You can't mock out exported functions - you can only mock properties on objects.

You either have to *not* mock `builder` - or, `export default` an object with properties, and make sure the "action" function looks up at runtime the "builder" function on that object. Then, you can mock out that object.

**Comment by awei01** [comment]
Actually, I ran into a similar issue and it is possible to mock these types of functions if you export/import all. It just depends on how you implement the called function and where you resolve that function:

your library `lib.js`
```
export function doSomething() { }
```

your method which calls the library `methods.js`
```
import * as lib from './lib'

export function useDoSomething(param) {
    const { doSomething } = lib
    return doSomething(param)
}
```

your tests
```
import * as lib from './lib'
import * as methods from './methods'
describe('methods using lib', () => {
  it('useDoSomething() called with [param] calls doSomething() with [param]', () => {
    spyOn(lib, 'doSomething')
    const { useDoSomething } = methods
    useDoSomething('foo')
    expect(lib.doSomething).toHaveBeenCalledWith('foo')
  })
})
```

**Comment by ljharb** [comment]
@awei01 if you're able to do that, it's a bug in babel, and your tests will likely break eventually. Exported functions can not be mocked.

**Comment by awei01** [comment]
@ljharb Thanks for the heads up. 

I suppose something like this would work then:

your library `lib.js`
```
function doSomething() { }
export default {
  doSomething
}
```

your method which calls the library `methods.js`
```
import lib from './lib'

export function useDoSomething(param) {
    const { doSomething } = lib
    return doSomething(param)
}
```

your tests
```
import lib from './lib'
import * as methods from './methods'
describe('methods using lib', () => {
  it('useDoSomething() called with [param] calls doSomething() with [param]', () => {
    spyOn(lib, 'doSomething')
    const { useDoSomething } = methods
    useDoSomething('foo')
    expect(lib.doSomething).toHaveBeenCalledWith('foo')
  })
})
```

**Comment by ljharb** [comment]
Yes, that's exactly what you'd have to do.

**Comment by awei01** [comment]
Looks like I'll be doing some refactoring.

**Comment by casertap** [comment]
@awei01 Lets imagine the doSomething function is defined at the same level as the useDoSomething.

Because that is the problem I am facing right now. What can I do?

**Comment by awei01** [comment]
@casertap You're going to have to refactor your file with exports. I believe this will work, but not tested. It's also a bit of an ugly hack, but I don't see any other way around it:

File with your library
```
const lib = {}

function doSomething(param) {
    const { useDoSomething } = lib
    return useDoSomething(param)
    // or return lib.useDoSomething(param)
}

function useDoSomething(param) {
    return param
}

lib.doSomething = doSomething
lib.useDoSomething = useDoSomething

**Comment by casertap** [comment]
Thanks, I will try that

**Comment by casertap** [comment]
I ended up using the inject-loader and moving the builder function in another file
```
const spy = expect.createSpy();
const module = require('inject!redux/modules/testedmodule')({
        'utils/build': {
          builder: spy
        }
      });
module.action()();
expect(spy.calls.length).toEqual(1);
 ```
of course in my testedmodule I have
```
import { builder } from 'utils/build'
export function action() { return () => builder() };
```

Is this a good way to do it, or am I complicating things here?

**Comment by awei01** [comment]
Fwiw, I suggest that if it's working as expected then add copious comments in your code detailing your thought process and leave it alone for now. Come back to it in a couple of weeks with fresh eyes and having developed/digested your more of your app.
