### ISSUE TITLE
Custom matchers

### ISSUE THREAD

**Issue by psmolinsky** [mjackson/expect#15]
Hello, is there a way how to extend your library and write custom match functions? For comparison Jasmine [supports it](http://jasmine.github.io/2.0/custom_matcher.html).

**Comment by rstacruz** [comment]
sure. here's one library that does it:

* https://www.npmjs.com/package/expect-html-equal
* https://github.com/rstacruz/expect-html-equal/blob/master/index.js

**Comment by psmolinsky** [comment]
Perfect, thanks.

**Comment by mjackson** [comment]
Please close issues when you consider them resolved, @psmolinsky :)
