### ISSUE TITLE
Bundle using Rollup?

### ISSUE THREAD

**Issue by mjackson** [mjackson/expect#150]
I've been wanting to try [Rollup](http://rollupjs.org/) for a while now. Maybe we could use it here to generate our UMD bundle?

**Comment by ljharb** [comment]
I'm still not sure why a UMD bundle is needed. Enabling people to not have their own module build systems isn't doing them any favors :-/

**Comment by bfred-it** [comment]
@ljharb: It's enabling [entry-level developers](https://twitter.com/SaraSoueidan/status/761320871566991360) to start testing without having to build castles.

**Comment by mjackson** [comment]
We could argue about the benefits of providing UMD builds here, but I'd rather not :) For me, it's a clear win. I'm just wondering if Rollup is a good tool to use to generate ours. Need to dig in and experiment.

**Comment by aMarCruz** [comment]
I think most users hate build their tools :)
Anyway, Rollup is the best bundler for libraries. In new versions of riotjs we are using Rollup + Bublé.

**Comment by ljharb** [comment]
Rollup violates the spec in at least one way I know of (`import *`); and now that v21+ is managed by jest, this package isn't going to change the way it does builds (that would risk a breaking change).
