### ISSUE TITLE
How to add to CodePen.io 

### ISSUE THREAD

**Issue by scheung38** [mjackson/expect#163]
https://egghead.io/lessons/javascript-redux-the-reducer-function

How to add library to CodePen.io after following the above tutorial? After adding in Settings -> Javascript Babel and then 

https://npmcdn.com/expect@1.20.2/umd/expect.min.js

It still doesnt work?

**Comment by ljharb** [comment]
Happy to keep discussing if you still have an issue; however, this isn't an actionable issue for this package.
