### ISSUE TITLE
expect([]).toEqual(false); does not throw

### ISSUE THREAD

**Issue by kfiroo** [mjackson/expect#165]
Hey!
Apparently this expression `[] == false` evaluates to `true` and so [TestUtils.js#L10](https://github.com/mjackson/expect/blob/master/modules/TestUtils.js#L10) returns `''` for `expect([]).toEqual(false)`

Is that the expected behaviour?
Why do we need to test using the abstract equality before calling `is-equal`?

Thanks

**Comment by skovhus** [comment]
I think this is fixed in expect@21 (maintained by Jest). : )

**Comment by ljharb** [comment]
If you're using `toEqual`, you want loose comparisons. If you want to compare to a primitive, use `.toBe`.
