### ISSUE TITLE
expect().inArray([42,21,3,7)

### ISSUE THREAD

**Issue by asmodehn** [mjackson/expect#166]
I just encountered a potential usecase that I don't think is currently covered by expect : 

I can run code that will randomly return something, like : 
```js
var myArray = ['A', 'B', 'C'];
var rand = myArray[Math.floor(Math.random() * myArray.length)];
```
This can be because randomness in code, like this example, but also randomness in execution (more complex). For example, I may want to test concurrency patterns, like a mutex, and execute multiple functions concurrently (with [async](http://caolan.github.io/async/docs.html#parallel)). I do not know which function will succeed or fail, so I want to expect "one in many" possible value.

So something like : 

```js
expect(rand).toBeIn(['A', 'B', 'C']);  //rand can only be 'A', 'B' or 'C'.
```

**Comment by ljharb** [comment]
Are you looking for `expect(arr).toInclude(rand)` ?

**Comment by asmodehn** [comment]
Ah true, I could do that with the inverse function... somehow didn't think about it. Thanks !
