### ISSUE TITLE
Object with index as keys should not equal array

### ISSUE THREAD

**Issue by astephenb** [mjackson/expect#17]
```javascript
expect({ 0: 'hello', 1: 'world' }).toEqual([ 'hello', 'world' ]);
```

I don't think this should pass, but it does. Is there something I am missing, or is this not intended?

**Comment by mjackson** [comment]
JavaScript arrays are actually [objects (with special semantics)](http://es5.github.io/#x15.4). I see no reason why that test shouldn't pass.

**Comment by aaronjensen** [comment]
Node core no longer agrees: https://github.com/nodejs/LTS/wiki/Breaking-changes-between-v0.12-and-next-LTS-release#assert-check-object-prototype-in-assertdeepequal

https://github.com/nodejs/node/pull/621

```js
Object.getPrototypeOf([0]) === Object.getPrototypeOf({'0': 0})
false
```
