### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by sdrabb** [mjackson/expect#182]
i'm trying to import the library, i try all the methods but i get this error

**GET http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false 500 (Internal Server Error)**

![image](https://cloud.githubusercontent.com/assets/15050464/21545636/741f6ba8-cdd9-11e6-9bdc-a4e456c44a8d.png)

how can i solve it?

**Comment by ljharb** [comment]
This seems to be an Android-specific React Native error - are you able to import other npm-installed modules?

**Comment by ljharb** [comment]
Happy to reopen if this is still an issue.
