### ISSUE TITLE
toNotHaveBeenCalled

### ISSUE THREAD

**Issue by gpbl** [mjackson/expect#19]
...is there a reason of why there's no such method?

**Comment by khronnuz** [comment]
Yes, looking for the same thing. Couldn't find a way to represent this.

**Comment by khronnuz** [comment]
Master have a commit that fixes this. We just need to wait until next version is released. I am already using this installing from source.

**Comment by mjackson** [comment]
This was added in 299ebe55d1f860ebdfa24d68f663cd2e33d699f5
