### ISSUE TITLE
toEquals does not match array of Symbols

### ISSUE THREAD

**Issue by mrsoto** [mjackson/expect#194]
This test fail

    describe('Having an array of Symbols', () => {
        const elementA = Symbol('A')
        const elementB = Symbol('B')

        it('toEqual should match', () => {
            expect([elementA, elementB]).toEqual([elementA, elementB])
        })
    }

**Comment by ljharb** [comment]
Can you include the failure message?

**Comment by ljharb** [comment]
As soon as travis-ci completes, I'll publish v1.5.5 of `is-equal` which will fix this for `expect` users on the next `npm install` after that.
