### ISSUE TITLE
Allow to manually destroy a spy

### ISSUE THREAD

**Issue by tkrotoff** [mjackson/expect#196]
Copy-paste of an [issue that I have with Jasmine/Jest](https://github.com/jasmine/jasmine/issues/1281).
Since expect mimics Jasmine API and [will be used by Jest](https://github.com/facebook/jest/issues/1679), I think it does no harm to discuss it here too.

---

Following the discussion on Google Groups: https://groups.google.com/forum/#!topic/jasmine-js/0RXvFo707EQ, I think my usecase is valid.

~~Jasmine~~ expect does not allow to manually delete/destroy a spy and this is limitating, use case:

```JavaScript
function signIn(done) {
  ...
  // Fails the 2x time with "<spyOn> : bar has already been spied upon"
  const mySpy = spyOn(foo, 'bar').and.callThrough();
  ...
  expect(foo.bar).toHaveBeenCalledTimes(1);

  // Missing feature:
  //mySpy.destroy();
}

function signOut(done) {
  ...
}

it('should be able to sign in/sign out multiple times', done => {
  signIn(() => {
    signOut(() => {
      signIn(() => { // Fails with "<spyOn> : bar has already been spied upon"
        done();
      });
    });
  });
});
```

signIn, signOut... are bricks (i.e simple functions - not Jasmine tests) that are reused to write complex Jasmine test scenarios like:
- signIn, doSomething1, signOut
- signIn, doSomething1, doSomething2, doSomething3, signOut
- signIn, signOut, signIn, signOut, signIn, signOut

Remarks:
- Currently the second signIn call fails with `<spyOn> : bar has already been spied upon`
- I cannot make spyOn global otherwise error `Spies must be created in a before function or a spec`
- Adding `beforeEach(()=> { spyOn(foo, 'bar').and.callThrough(); })` is not the solution because `expect(foo.bar).toHaveBeenCalledTimes(1)` will fail with the 2x signIn call (because `.toHaveBeenCalledTimes(2)`)

**Comment by ljharb** [comment]
does `spy.restore()` not work? That's how `sinon` does it.

**Comment by tkrotoff** [comment]
@ljharb Oh you are right! `spy.restore()` works perfectly! thx a lot

To sum up: Jasmine is missing `restore()`

Working example:

```TypeScript
import { spyOn } from 'expect';
import * as expect from 'expect';

class Foo {
  bar(msg: string | number) {
    console.log('foo bar', msg);
  }
}

const foo = new Foo();

function loadApis(done: () => void) {
  console.log('loadApis');
  done();
}

let msgCount = 0;

function signIn(done: () => void) {
  console.log('signIn');

  const spy = spyOn(foo, 'bar').andCallThrough();
  foo.bar(msgCount++);
  expect(spy).toHaveBeenCalled();
  expect(spy.calls.length).toEqual(1);
  spy.restore();

  done();
}

function signOut(done: () => void) {
  console.log('signOut');
  done();
}

test('multiple sign in / sign out', done => {
  loadApis(() => {
    signIn(() => {
      signOut(() => {
        signIn(() => {
          signOut(() => {
            done();
          });
        });
      });
    });
  });
});
```

if line `spy.restore()` is commented:
```TypeScript
  const spy = spyOn(foo, 'bar').andCallThrough();
  foo.bar(msgCount++);
  expect(spy).toHaveBeenCalled();
  expect(spy.calls.length).toEqual(1);
  //spy.restore();
```
it fails as expected at line `expect(spy.calls.length).toEqual(1)`: `Expected 2 to equal 1`
