### ISSUE TITLE
toEqual() does not differentiate ['value'] and 'value'

### ISSUE THREAD

**Issue by paladan** [mjackson/expect#198]
Found this while writing a test the other day. We were asserting that the result of a function returned the string value from a provided property in an array:

`
expect(returnedValue).toEqual('expected-value')
`

Interestingly, this same assertion passed, and we found that the function was actually returning the value wrapped inside of an array:

`
expect(returnedValue).toEqual(['expected-value'])
`

It doesn't make much sense to me that both these assertions should return true. Is this expected behavior?

**Comment by ljharb** [comment]
iirc loose equal stringifies the array, which makes them equivalent.

**Comment by jharris4** [comment]
just hit this same issue when using the new version of expect (coming from Jest).

The difference seems to be because the old expect uses the `is-equal` package which allows things like `expect(["abc"]).toEqual("abc")` whereas the jest toEqual does not...

**Comment by ljharb** [comment]
Issues with v21+ of expect need to be filed in the jest repo: https://github.com/facebook/jest
