### ISSUE TITLE
Expect function with arguments to throw error

### ISSUE THREAD

**Issue by anton-johansson** [mjackson/expect#2]
Hi!

Really love this project, decided to use it for all my asserts/expectations in my unit tests. I'm quite new to it, though, so this issue might be misplaced. Let me know if this functionality already exists, but I couldn't find any.

There is one thing I'm lacking that I noticed existed in another expect framework ([expect.js](https://github.com/Automattic/expect.js)). It is this:
`expect(fn).withArgs(invalid, arg).to.throwException();`

Because currently, using this framework, I have to write:
`expect(function () { myFunction(invalidArgument); }).toThrow(/some error message/);`

It would be nice if you could write:
`expect(myFunction).withArgs(invalidArgument).toThrow(/some error message/);`

... or even (however, above is probably more clear):
`expect(myFunction, invalidArgument).toThrow(/some error message/)`

**Comment by mjackson** [comment]
@anton-johansson Sure, we could add a `withArgs` method to the `Expectation` prototype. Would you like to take a shot at a PR?

**Comment by JohnnyEstilles** [comment]
@mjackson, I'd be willing to work a a PR for to add `.withArgs()` to `Expectation` if you and @anton-johansson are still interested.

**Comment by JohnnyEstilles** [comment]
Can I also suggest adding the ability to optionally provide an object as context. Something line `.on(context)` or `.calledOn(context)`

For example:
```js
expect(myFunction).calledOn(context).withArgs(invalidArgument).toThrow(/some error message/);
```

**Comment by mjackson** [comment]
We now have both `withContext` and `withArgs` in master.

**Comment by anton-johansson** [comment]
Nice work! :)
