### ISSUE TITLE
expect(<instance function>) and automatically set context

### ISSUE THREAD

**Issue by anton-johansson** [mjackson/expect#21]
Hi!

I'm not sure if this is actually possible, so just close it if it's not.

In #2 we got support for using ```.withArgs(...)``` and ```.withContext(...)```, which is awesome. When using instance methods, it would be nice if the context could be set automatically. For example, currently I have to write:

```js
var myInstance = new MyClass();
expect(myInstance.myFunction).withContext(myInstance).withArgs(...).toThrow(/some error message/);
```

Is it possible to set the context from the method directly?

**Comment by mjackson** [comment]
No, from the method we can't get a reference back to the object it is defined on.

**Comment by rstacruz** [comment]
I think that's better written as:

```js
expect(() => myInstance.fart()).toThrow(/out of gas/)
```
