### ISSUE TITLE
expect(<constructor>).toThrow(/some message/);

### ISSUE THREAD

**Issue by anton-johansson** [mjackson/expect#22]
I'd like to use this pattern:
```js
expect(MyClass).withArgs(1, 2, 3).toThrow(/Invalid arguments/);
```

But since you need to use the ```new``` keyword to properly call this constructor, it doesn't quite work out. Any ideas on how this can be solved?

Maybe a new keyword:
```js
expect(MyClass).constructor().withArgs(1, 2, 3).toThrow(/Invalid arguments/);
```

**Comment by mjackson** [comment]
Why don't you just

```js
expect(function () {
  new MyClass(1, 2, 3)
}).toThrow(/Invalid arguments/)
```

No special keyword needed :)

**Comment by mjackson** [comment]
If you really care about making it concise, use babel to transpile your code and an ES6 arrow function:

```js
expect(() => new MyClass(1, 2, 3)).toThrow(/Invalid arguments/)
```

**Comment by mjackson** [comment]
Closing since there hasn't been any activity here for a while.
