### ISSUE TITLE
spawn_id exp6 error message

### ISSUE THREAD

**Issue by bobbyditigal** [mjackson/expect#221]
My team has a script that will change passwords for devices that we manage, however I am the only person on the team that script will not run successfully for.  I receive the following error message when I run the scripts.  At first I thought there was something wrong with my unix profile but I notice that ssh never spawns.  I can ssh from my unix server successfully to the other servers.  

Open a second terminal session and tail -f chngcliuserpw.062717105302.out
 xecuting chngcliuserpw.exp ON device1
parent: waiting for sync byte
parent: telling child to go ahead
parent: now unsynchronized from child
spawn: returns {29331}

expect: does "" (spawn_id exp6) match glob pattern "password: "? no
"Are you sure you want to continue connecting (yes/no)?"? no
expect: read eof
expect: set expect_out(spawn_id) "exp6"
expect: set expect_out(buffer) ""

**Comment by ljharb** [comment]
This isn't related to this JavaScript library - you may be looking for a different project.
