### ISSUE TITLE
No readme on npmjs.com

### ISSUE THREAD

**Issue by BurtHarris** [mjackson/expect#223]
Are you aware the README for your package does not show up at https://www.npmjs.com/package/expect?

**Comment by ljharb** [comment]
Likely because of using the "files" property in package.json. We should remove that, and use .npmignore instead to restrict what gets published.

**Comment by ljharb** [comment]
The v21+ versions of expect are now maintained by jest; please file this there.

Versions of expect prior to v21 will be maintained in this repo; but their readmes will never show up on npmjs.com.
