### ISSUE TITLE
toBeA() not functioning as expected.

### ISSUE THREAD

**Issue by thesemicolonguy** [mjackson/expect#233]
![screenshot from 2017-10-06 13-54-09](https://user-images.githubusercontent.com/22498965/31269469-2bcf0e56-aa9e-11e7-93de-1549239ff1a1.png)

`expect(5).toBeA('number');`

is giving error: `TypeError: expect(...).toBeA is not a function`

It should work according to documentation [here](https://github.com/mjackson/expect#tobeastring)

**Comment by ljharb** [comment]
expect v21+ is now part of jest; please file issues on that repo.
