### ISSUE TITLE
toBeA() function, throwing an 'undefined' error

### ISSUE THREAD

**Issue by eazylaykzy** [mjackson/expect#237]
I've been trying to figure out what went wrong with my code for the past few hours, but i think the `toBeA()` is giving this the below error message:

  _**1) should add two number:
     TypeError: Cannot read property 'toBeA' of undefined
      at Context.it (utils\utils.test.js:7:23)**_

Below is the actual code:

```
const expect = require('expect');
const utils = require('./utils');

it('should return the square of the number', () => {
  let res = utils.square(5);

  expect(res).toBe(25).toBeA('number');
});
```

**Comment by ljharb** [comment]
What version of `expect` are you using? v21+ is now managed by [jest](https://github.com/facebook/jest)

**Comment by eazylaykzy** [comment]
Yes @ljharb , I'm using v21+
After going through the **_Readme Notice_** Github page, I found out the package has been donated to Facebook Jest, so i did a little search query on it, and fixed it with the code below:

```
it('should return the square of the number', () => {
  let res = utils.square(5);

  expect(res).toBe(25);
  expect(typeof res).toBe('number');
});
```

Thanks @ljharb
