### ISSUE TITLE
toBeA() returns an error saying it is not a function or cannot read property of

### ISSUE THREAD

**Issue by davidshare** [mjackson/expect#240]
I'm trying to check if the result of a function is a number, and it keeps returning an error that it cannot read property toBeOf undefined. Here is the code

it('should square a numbers', ()=>{
	let res = utils.square(5);
	expect(res).toBe(25).toBeA('number');
});

![image](https://user-images.githubusercontent.com/25446108/34459674-f405f9de-edf6-11e7-8d91-d1ab5097e5bc.png)

**Comment by ljharb** [comment]
Which version of `expect` are you using? v21+ is managed by jest.

**Comment by MatthewKosloski** [comment]
I get same error with `expect` 22.0.6.

![](https://i.imgur.com/Qw9YYT4.png)

Copied the code straight from the [README.md](https://github.com/mjackson/expect#tobeastring)

```js
describe('Unit Test', () => {
	it('should not fail...?', () => {
		expect(2).toBeA('number');
	});
});
```

**Comment by MatthewKosloski** [comment]
Nevermind!  Referenced from [here](https://github.com/mjackson/expect/issues/237#issuecomment-346993012)

Test passed with:

```js
describe('Unit Test', () => {
	it('should not fail...?', () => {
		expect(typeof 2).toBe('number');
	});
});
```

**Comment by ljharb** [comment]
@MatthewKosloski expect v21+ is managed by the jest team; that includes v22.
