### ISSUE TITLE
.toBeA() isn't functioning

### ISSUE THREAD

**Issue by hamzanaveedmalik** [mjackson/expect#243]
I've just used the function `.toBeA('number')` in my code and it's not working. I'm using it concatenated with `.toBe(4).toBeA('number')`

**Comment by ljharb** [comment]
@hamzanaveedmalik what version of expect are you using? v21+ is maintained by jest; this repo is for versions < 21.

**Comment by edbutcher** [comment]
I have used an "expect(2).toBeA('number')" in "expect": "^22.1.0" and it gives me the error.

**Comment by ljharb** [comment]
@edbutcher expect v21+ is maintained by jest; and thus is not this repo.

**Comment by edbutcher** [comment]
Sorry, @ljharb . I haven't read the "Notice" section... I'm using version "expect": "^1.20.2" and everything works fine.
