### ISSUE TITLE
TypeError: Cannot read property 'toBeA' of undefined

### ISSUE THREAD

**Issue by jbraide** [mjackson/expect#247]
Hello,
i'm trying to use your awesome Library but I came across this error in the title,
in order to make my code work I had to revert to an older version , 1.20.1 to be precise.
For the sake of others who would use your middleware in the future please can this be addressed.
Thanks
Joseph
![screenshot from 2018-06-16 09-43-34](https://user-images.githubusercontent.com/40149596/41497286-28ea2374-714a-11e8-9753-e3ebde8dcd0c.png)

**Comment by ljharb** [comment]
expect v21+ is managed by the jest team, as is mentioned on the readme, and lives in another repo.
