### ISSUE TITLE
“test is not defined” jest/expect on client side

### ISSUE THREAD

**Issue by IndusFireTiger** [mjackson/expect#250]
I get "test is not defined" Uncaught ReferenceError on the browser.

I dont use ESLINT, which according to [this link](https://stackoverflow.com/questions/44479207/prevent-test-expect-etc-is-not-defined-errors-when-using-jest/44479250)is the solution to "test is not defined". "test" which is a global in jest/expect testing library, it is expected to be available after the including the expect.min.js file in the test.html

In that case what could be the other reasons and their solution.

here is my code:
    <script src="https://unpkg.com/expect@%3C21/umd/expect.min.js"></script>
    <script src='script.js'></script>
    <script>
      test('myTest', () => {
        a = {}
        b = {}
        a.rating = 1
        b.rating = 2
        expect(sortAlgo(a,b)).toBe(1)
      })
   </script>

**Comment by ljharb** [comment]
What version of expect are you using? That looks like v21 - v21+ of expect is a different project maintained by the jest team, per the readme: https://github.com/mjackson/expect#notice

**Comment by IndusFireTiger** [comment]
As suggested in the https://github.com/mjackson/expect#installation, I am using this link <script src="https://unpkg.com/expect@%3C21/umd/expect.min.js"></script>

So according to you 'test' is not available on expect older version. But according to Jest official docs https://jestjs.io/docs/en/expect#reference 'test' is a global. This could mean that test is available only on the higher versions of expect.

If so can you suggest the library link to the version where I can use 'expect' along with 'test'.

**Comment by ljharb** [comment]
Yes, it’s in the read me which i linked. Please read it :-)
