### ISSUE TITLE
(...).toExist is not a function

### ISSUE THREAD

**Issue by leoggonzalez** [mjackson/expect#251]
I'm getting this error when calling .toExist();

`expect('something truthy').toExist();`

`TypeError: (0 , _expect2.default)(...).toExist is not a function
        at Context.eval (webpack-internal:///42:27:47)`;

Other methods work just fine

**Comment by ljharb** [comment]
That's because `.toExist` is part of jest's expect package, which is v21+ (see the readme). This repo is for versions < 21.
