### ISSUE TITLE
Cannot include module 'expect'

### ISSUE THREAD

**Issue by amanpreets01** [mjackson/expect#252]
Tried command to install:
//npm install expect
//npm install expect@1.20.2
//npm install expect@1.20.2 --save-dev

Nothing works.Please help me on this.Any help would be appreciated

**Comment by ljharb** [comment]
That should be sufficient; I’m not sure what you mean by “nothing works”.

**Comment by amanpreets01** [comment]
There was an internal issue and I solved it .Thank you for the reply .I appreciate it
