### ISSUE TITLE
Consider standard and mocha-standard

### ISSUE THREAD

**Issue by rstacruz** [mjackson/expect#27]
http://standardjs.com/

your eslint style is almost exactly like standard, except spaces after the function keyword is enforced in standard (`function ()` vs `function()`).

**Comment by mjackson** [comment]
We already [enforce spaces before anonymous function parens and don't require them for named functions](https://github.com/mjackson/expect/blob/master/.eslintrc#L22).

I agree that my style is similar to standard, but I prefer to use ESLint.
