### ISSUE TITLE
Show object diffs in Mocha

### ISSUE THREAD

**Issue by rstacruz** [mjackson/expect#29]
Here's a comparison of how Chai and Expect handles object diffs. Notice how it's very readable with the diff being shown.

![pasted_image_10_5_15__3_09_am](https://cloud.githubusercontent.com/assets/74385/10269570/71cf6684-6b0e-11e5-9e18-a369a6531c09.png)

made using this code:

```js
describe('object comparison', function () {
  it('via chai', function () {
    var expect = require('chai').expect
    expect({a:1,b:2,c:3}).to.eq({a:1,b:2,c:4})
  })

  it('via expect', function () {
    var expect = require('../index')
    expect({a:1,b:2,c:3}).toEqual({a:1,b:2,c:4})
  })
})
```

**Comment by rstacruz** [comment]
Chai throws an assertion error in this format:

```js
{ [AssertionError: expected { a: 1, b: 2, c: 3 } to equal { a: 1, b: 2, c: 4 }]
  message: 'expected { a: 1, b: 2, c: 3 } to equal { a: 1, b: 2, c: 4 }',
  showDiff: true,
  actual: { a: 1, b: 2, c: 3 },
  expected: { a: 1, b: 2, c: 4 } }
```

**Comment by mjackson** [comment]
Fixed in #30

**Comment by Anahkiasen** [comment]
Anything similar possible for Karma?

**Comment by mjackson** [comment]
Karma just runs browsers and reports the results to the console. Use mocha with karma to get these doffs in the console.

**Comment by thenickcox** [comment]
For anyone finding this via Google, [karma-mocha-reporter](https://www.npmjs.com/package/karma-mocha-reporter) provides this functionality, and is pretty much drop-in.
