### ISSUE TITLE
Add a note about comparison with other libraries

### ISSUE THREAD

**Issue by rstacruz** [mjackson/expect#31]
There are other popular assertion libraries out there such as [chai](https://www.npmjs.com/package/chai) and [expect.js](https://www.npmjs.com/package/expect.js). Perhaps there should be an explanation that compares `expect` to these libraries.

Personally, here's my take:

1. I find the `.toBeAn('object')` neater than `.to.be.an('object')` since it enforces a one standard way of writing an assertion. I see people often write both `expect().to.eq()` and `expect().eq()` interchangeably, which are equivalent in those libraries.

2. Since `expect` doesn't rely on Object.defineProperty getters, it is compatible with legacy IE versions.

3. `expect` comes with built-in spies and mocking.

**Comment by mjackson** [comment]
Yes, that would be a great addition to the README.

**Comment by mjackson** [comment]
You have time to add this, @rstacruz? Or you want me to take a shot?

**Comment by rstacruz** [comment]
go ahead!
