### ISSUE TITLE
Expose `Expectation.prototype`

### ISSUE THREAD

**Issue by rstacruz** [mjackson/expect#32]
Ever since `expect` was refactored to ES6, `Expectation` is now not part of the public API. This means you can't write `expect` plugins anymore. [expect-html-equal](https://www.npmjs.com/package/expect-html-equal) is one that's particularly affected by this change.

I'd love to see other plugins for expect to compare HTML (like [expect-html-equal](https://www.npmjs.com/package/expect-html-equal)), make jQuery assertions (like [chai-jquery](https://www.npmjs.com/package/chai-jquery)), compare CSS colors (like [chai-colors](https://www.npmjs.com/package/chai-colors)), compare numbers with a certain precision (like [this](https://github.com/magwo/expect.js/commit/105caeadbd375aeb041ccdeee88ffc55a58fe2e3)), and so on.

**Comment by rstacruz** [comment]
For comparison, this is how chai is extended:

```js
chai.Assertion.addMethod('myplugin', function (colorString) {
  this.assert(a === b,
    'expected #{act} to be like #{exp}',
    'expected #{act} to not be like #{exp}',
    a, b)
})
```

**Comment by mjackson** [comment]
I wonder if we could do something really simple like:

```js
expect.toBeGreaterThanOrEqualTo = function (actual, expected) {
  invariant(
    actual >= expected
  )
}
```

**Comment by rstacruz** [comment]
`expect` seems like a strange namespace (that's where `createSpy` et al are at), how about `expect.fn`? you can also expose `invariant` as `expect.assert()`.

```js
expect.fn.toHaveLength = function (len) {
  assert(this.actual.length === 'len',
    'expected %s to have length %s',
    this.actual, len)
}
```

this'd be easy to implement:

```js
expect.fn = Expectation.prototype
expect.actual = require('./invariant')
```
