### ISSUE TITLE
Commit the UMD build to the repo

### ISSUE THREAD

**Issue by rstacruz** [mjackson/expect#33]
This is more of a personal preference... but I'd love to see the UMD build accessible via http://rawgit.com/ for easy in-browser testing.

The alternative is to use wzrd.in (https://wzrd.in/standalone/expect@latest) but I find that that site is a little less reliable than rawgit.

Example: http://rawgit.com/rstacruz/nprogress/master/test/index.html

**Comment by mjackson** [comment]
I'd rather not commit auto-generated files to git if we can help it, at least not to the master branch. Maybe we could create a special branch that contains the pre-built files, perhaps using something like [`publish-latest`](https://www.npmjs.com/package/publish-latest)...

**Comment by rstacruz** [comment]
:+1: for publish-latest

**Comment by vvo** [comment]
Maybe publish this cool project to jsdelivr so people wanting to use `<script>` will be happy

**Comment by mjackson** [comment]
I just submitted a PR to cdnjs https://github.com/cdnjs/cdnjs/pull/5946. It should be available within 30 hours.
