### ISSUE TITLE
Why include spies?

### ISSUE THREAD

**Issue by vvo** [mjackson/expect#38]
I am wondering what was the motivation to include test spies inside the library? Sinon.js already has a very good experience and API for spies, stubs, mocks.

I fear that what we will endup in expect is a somehow subset of sinon.js but less powerful.

What do you think? I would remove the test spy API. BTW Sinon.js is close to be working with ES6, master is currently working.

**Comment by mjackson** [comment]
expect is a library for writing assertions. That's it. Spies are a way to write assertions about the way that functions are called. So we include them.

I personally don't use sinon.js, and haven't ever needed it. So I'd hate to remove something in expect that is already working well for a lot of people and recommend they install some other lib that they've never needed.

**Comment by rstacruz** [comment]
> I fear that what we will endup in expect is a somehow subset of sinon.js but less powerful.

I personally don't mind this. You can use sinon with expect if you like its fancier features like fake XmlHTTPRequests and such, and we can write a sinon adaptor for expect in the future.

Think of it as you get a lightweight spy library out of your out-of-the-box expect experience; you can always upgrade it later.

**Comment by vvo** [comment]
Yup I get it. Its just than after using sinon and seeing the expect
