### ISSUE TITLE
`toInclude` does not use `deepEqual`

### ISSUE THREAD

**Issue by kentor** [mjackson/expect#45]
Docs for `toInclude` says if `comparator` is not provided, it defaults to `assert.deepEqual` https://github.com/mjackson/expect#toinclude 

But I believe it's just doing an `indexOf` comparison instead of `assert.deepEqual`.

PR: https://github.com/mjackson/expect/pull/44

FYI: jasmine's `toContain` uses deepEqual

**Comment by mjackson** [comment]
Fixed in #44. Thanks, @kentor!
