### ISSUE TITLE
Send the error in the callback

### ISSUE THREAD

**Issue by IonicaBizau** [mjackson/expect#61]
Is there something like this?

```js
expect(42).toBe(7, function (err) {
   /* do something with the error, but call this only if there is an error */
});
```

**Comment by rstacruz** [comment]
```js
try {
  expect(42).toBe(7)
} catch (err) {
  // raise havoc and pandemonium
}
```

**Comment by IonicaBizau** [comment]
@rstacruz Obviously yes (thanks!), but I would like to have this built-in as feature in the library, otherwise I will probably create an `expect-async` or something like that. :smile:

**Comment by rstacruz** [comment]
alright... though I'm not sure I understand the use case. is this something you'd see in expectjs/chai/etc?

**Comment by mjackson** [comment]
@IonicaBizau Feel free to create an extension that does this, but it's not something I'd like to include here. We already reserve the remaining arguments for error messages. I'd hate to overload the argument list.

**Comment by IonicaBizau** [comment]
I agree with that, @mjackson! Thanks. :+1:
