### ISSUE TITLE
expect(null).toEqual(undefined) failing since 1.13.1

### ISSUE THREAD

**Issue by taurose** [mjackson/expect#62]
This was causing me some issues with rackt/history.

It looks like this test passed before 1.13.1 with `deep-equals` but fails with `is-equal`. 

I don't know how you want this case to be handled, but since it's a minor version bump, I assume it wasn't intentional. Otherwise, feel free to close.

**Comment by mjackson** [comment]
I naively assumed that `is-equal` would handle all the most common cases similarly to `deep-equal` but I was mistaken. The break wasn't intentional, but now that we've worked out most of the kinks let's just add a test to make our intention clear and close.

**Comment by ljharb** [comment]
`null` and `undefined` aren't equal - isn't `toEqual` like `===`?

**Comment by mjackson** [comment]
Yes, it is. We should just add a test here to make that clear and close.

**Comment by ljharb** [comment]
:+1:

**Comment by mjackson** [comment]
Wait, I'm not sure what I was saying here. `toEqual` should be like `==`. `toBe` is for `===`.

**Comment by ljharb** [comment]
oh right, good point
