### ISSUE TITLE
wrong expectation

### ISSUE THREAD

**Issue by janusch** [mjackson/expect#67]
Hey Michael,

I was wondering about your expect library. First I thought that I was using it when writing tests in mocha/chai. But apparently that is a different expect lib, right? The syntax looks slightly different.

Maybe it would be beneficial to clarify that in the top of the readme? Also to note that this expect lib fills some shortcomings, that you encountered with mocha/chai's expect. 

Is there no need for sinon.js or chai anymore if one uses your expect?

I do understand the tag line "expect lets you write better assertions." I just do not understand the context; better than what?

Would be very nice if you had the time to clarify this!
Cheers

**Comment by mjackson** [comment]
Better than just a plain `assert` ;)

Sure, I'll clarify what I mean in the README.
