### ISSUE TITLE
Spies do not call the underlying function by default

### ISSUE THREAD

**Issue by danny-andrews** [mjackson/expect#69]
Example:

```js
var a = {
  return4: function() {
    return 4;
  }
};
console.log(a.return4()); // prints "4"
var spy = expect.spyOn(a, 'return4');
console.log(a.return4()); // prints "undefined"
```

**Comment by ljharb** [comment]
This is how spies typically work. You want `.andCallThrough` if you want the original function to be called (it's not invoked *at all* in your example, which you can verify with a `console.log`), or `.andReturn` to return a specific value, etc. See https://github.com/mjackson/expect#spy-methods in the readme.

**Comment by vvo** [comment]
Actually here we are doing smg different than a well known library, wich is sinonjs. In sinonjs you have spies: they do not alter the underlying implementation. And stubs: they replace the underlying implementation with what you want.

Also #38 :)

**Comment by mjackson** [comment]
The spy implementation in expect is patterned after spies in jasmine, not sinon. By default, spies return `undefined`.

I guess technically we *could* call the underlying function by default, but that would be a major breaking change. It could eliminate the need for `.andCallThrough` altogether, though. Which is cool.

**Comment by ljharb** [comment]
Personally I find the vast majority of the time, if I'm making my tests more brittle by adding spies and mocks, i *don't* want to call through. Ideally, tests test one thing, whether it's "the method was called" or "the method's effects happened". Obv that's subjective tho.

**Comment by mjackson** [comment]
Ya, @ljharb. I'd agree w that. Gonna close this for now since most of the time you're using spies you probably don't want to call through. Use `.andCallThrough` if you do.
