### ISSUE TITLE
Confusing assertion message with different prototypes

### ISSUE THREAD

**Issue by Kos** [mjackson/expect#70]
Given a test:

```  
  it("should give helpful messages", function() {
    function Foo() {this.x = 10;}
    let a = {x: 10};
    let b = new Foo();
    expect(a.constructor).toBe(Object);
    expect(b.constructor).toBe(Foo);
    expect(a).toEqual(b);
  });
```

the test fails (rightfully) on the last assertion, but the message gives you:

```
      Error: Expected { x: 10 } to equal { x: 10 }
      + expected - actual
```

which isn't helpful.

Shouldn't the message tell me that the objects compare as different because they have a different constructor?

**Comment by ljharb** [comment]
Currently, `is-equal` returns a boolean, so this info might be hard to detect. However, I could see a parallel API that returned a *reason* for not being equal. @mjackson, let me know if this is something you'd find helpful here.

**Comment by Kos** [comment]
Another way around that could possibly be to detect the situation "X and Y compare as different but the resulting diff is empty" and work out a different message in that case.

**Comment by ljharb** [comment]
I ended up making this anyways - upgrade to `v1.5.0` of `is-equal`, and `require('is-equal/why')` to get a function that returns the empty string when `is-equal` would return `true`, otherwise it returns a string with the reason for the inequality.

**Comment by mjackson** [comment]
Thanks, @ljharb.

Turns out generating good default error messages is one of this library's main responsibilities; something I didn't really anticipate when I first built it.

I'm happy to accept a PR if you'd like to take a shot at a better error message here @Kos.

**Comment by mjackson** [comment]
Closing this for now. Please feel free to make a PR if it's a pain point.
