### ISSUE TITLE
expect 1.15 breaks builds

### ISSUE THREAD

**Issue by rstacruz** [mjackson/expect#72]
expect 1.15 is not backwards compatible with old releases:

```js
var expect = require('expect')
expect(3).toEqual(2)

/* TypeError: expect is not a function */
```

I suggest unpublishing 1.15.0, 1.15.1 and republishing them as 2.0.0 instead, or correcting this behavior.

**Comment by rstacruz** [comment]
This is because the new exports:

```js
export default expect

export {
  assert,
  extend,
  createSpy,
  spyOn,
  isSpy,
  restoreSpies
}
```

...in Babel desugars into:

```js
module.exports = {
  assert,
  extend,
  createSpy,
  spyOn,
  isSpy,
  restoreSpies
}

module.exports.expect = expect
```

The way around this is to not use Babel's `export` but instead use `module.exports`.

**Comment by vvo** [comment]
> The way around this is to not use Babel's export but instead use module.exports = expect.

Yes if you want the lib to be usable by non ES6 ppl, then you need to use the module.exports at the very end

**Comment by krzysu** [comment]
+1, it broke all my server side tests, please be careful with versioning

**Comment by gagern** [comment]
Please try to [follow semver](http://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version):

> *What do I do if I accidentally release a backwards incompatible change as a minor version?*
>
> As soon as you realize that you’ve broken the Semantic Versioning spec, fix the problem and release a new minor version that corrects the problem and restores backwards compatibility. Even under this circumstance, it is unacceptable to modify versioned releases. If it’s appropriate, document the offending version and inform your users of the problem so that they are aware of the offending version.

So I'd say we need 1.16 to fix this problem, and 1.15 documented as breaking things.

**Comment by ljharb** [comment]
ok, relax people, clearly it was a mistake, and clearly the fix is to use `module.exports` in the entry point or to use a babel transform to do the same. @mjackson will likely have a fix out today.

**Comment by ljharb** [comment]
I'll have a v1.15.2 out in an hour or so.

**Comment by ljharb** [comment]
v1.15.2 published, and I've deprecated v1.15.0 and v1.15.1.

Sorry for the inconvenience!

**Comment by mjackson** [comment]
Thanks, @ljharb! I obviously don't understand ES6 modules very well. Or maybe Babel. I didn't realize that using named exports would clobber `module.exports`. But it makes sense that it does.

**Comment by ljharb** [comment]
It's a change in babel 6's CJS interop that it always has `.default`, but adding the named exports would have broken it in babel 5 also.
