### ISSUE TITLE
Support expect(array).toInclude(arrayOfElements) assertion?

### ISSUE THREAD

**Issue by viniciusbo** [mjackson/expect#88]
Would the following be considered useful?

```javascript
expect([1, 2, 3]).toInclude([1, 3])
```

If so I'd be happy to submit a pull request.

**Comment by mjackson** [comment]
That feature would make it difficult to test for an array as a value inside another array, like this:

```js
expect([ 1, 2, [ 3 ] ]).toInclude([ 3 ])
```

**Comment by viniciusbo** [comment]
Actually the the most meaningful way for me to this assertion would be

```javascript
expect([ 1, 2, [ 3 ] ]).toInclude([ [ 3 ] ])
```
