### ISSUE TITLE
Support for spying on getters/setters

### ISSUE THREAD

**Issue by grrowl** [mjackson/expect#89]
Some libraries (in this case, `react-router-redux`) defines a getter (`replace`) which we'd like to spy on. It actually returns a singleton. We don't care, we just want to spy on it, and call through.

Is this possible?

**Comment by ljharb** [comment]
We'd probably want a separate `spyOnGetter`/`spyOnSetter` function, so it would explicitly wrap the `get`/`set` descriptor values, and would throw in envs that don't support property descriptors.

**Comment by grrowl** [comment]
There's [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), supported in the latest Chrome but not Node, probably not useful until wider adoption

**Comment by mjackson** [comment]
I wonder if we could just augment `spyOn` to be smart about this, so e.g. if I say `spyOn(object, 'replace')` we can use `getOwnPropertyDescriptor` to figure out if it's a getter or whatever and do the right thing.

**Comment by ljharb** [comment]
We totally could - but I don't think that would be a better API. What if I'm trying to spy on a getter with a non-getter?

Also, ES3 envs (that all my modules still work in) can't use getters/setters, so having a separate API makes the split clearer imo.

**Comment by mjackson** [comment]
Ya, I agree w you. spyOnGetter/Setter sounds like the way to go.

**Comment by mjackson** [comment]
@grrowl Would you like to take a shot at a PR here?

**Comment by grrowl** [comment]
Looks like we can't reassign the property if it's not `configurable` (which is the default for `defineProperty`).

```
> Object.getOwnPropertyDescriptor(object, methodName)
= { get: function get() { ... }, set: undefined, enumerable: false, configurable: false }
```

Throws a `TypeError: Cannot redefine property: play`

**Comment by ljharb** [comment]
Since it only throws in sloppy mode, you'd definitely want to explicitly throw when a property that's attempted to be spied on is nonconfigurable. This check may not be being done for the normal spies too.

**Comment by grrowl** [comment]
I'm not so personally invested in this anymore as the `configurable: false` limitation has pushed me to rewrite my tests without spying on these methods. If you're still interested in this feature I can still finish off this PR though — up to you.

**Comment by mjackson** [comment]
Seems like there are some edge cases here that I don't want to deal with for now. Thanks for bringing it up though. We may revisit at some point in the future if someone comes along who really wants/needs it.
