### ISSUE TITLE
How to get result from "expect" function

### ISSUE THREAD

**Issue by Alexml8456** [mjackson/expect#92]
Guys hello.
Help me please understand how I can get a result (passed or failed) from "expect" function.
I have such example code:

    describe("Regression tests", function() {

    it("Test1", function() {
        expect("Implementation-Title").toContain("Title");
        if (expect("Implementation-Title").toContain("Title") == 'passed'){
            //Do some actions;
        }
        else{
            //Do some actions;
        }});

    it("Test2", function() {
        expect(2).toEqual(2);
        if (expect(2).toEqual(2) == 'passed'){
            //Do some actions;
        }
        else{
            //Do some actions;
        }
    });});

How I can get a result (passed or failed) for each "it" and then, depends on result, do some actions?

I need to validate exceptions and if it's present, I need to do some actions (for example send exception to TestRail).

Thanks for support

**Comment by ljharb** [comment]
Expectations throw when they fail, so any code after an expectation that executes means all the previous expectations passed.

What's your real-world need for executing code conditionally when expectations fail?

**Comment by Alexml8456** [comment]
This is my real code:

    var Login = require('./../login/login.page.js');
    var TopmenuPage = require('../menu/top-menu.page.js');
    var TestRail = require("node-testrail");
    var testrail = new TestRail("http://192.168.2.414/testrail", "user", "password");

    describe('Login scenario: ', function () {
    var loginPage;

    beforeEach(function () {
        loginPage = new Login();
    });

    afterEach(function() {
        browser.manage().deleteAllCookies();
    });

    it('should successfully log in', function () {
        loginPage.login(browser.params.user,browser.params.password);
        expect(TopmenuPage.logoutButton.isPresent()).toBe(true);
        expect(TopmenuPage.welcome).toContain("Welcome " + browser.params.user);
        if ("failed"){
            testrail.addResult(16620, "5", "This test failed", "test", "", "", "", function(body) {
                console.log(body);});
        }
        else{
            testrail.addResult(16620, "1", "This test passed", "test", "", "", "", function(body) {
                console.log(body);});
        }
    });

    it('should fail to login user with wrong permissions', function () {
        loginPage.login('user2',browser.params.password);
        expect(loginPage.dangerAlert).toContain("Authentication Failed: User does not have required permissions");
        if ("failed"){
            testrail.addResult(16621, "5", "This test failed", "test", "", "", "", function(body) {
                console.log(body);});
        }
        else{
            testrail.addResult(16621, "1", "This test passed", "test", "", "", "", function(body) {
                console.log(body);});
        }
    });

    it('should fail to login user with wrong credentials', function () {
        loginPage.login('test_user','test_user');
        expect(loginPage.dangerAlert).toContain("Invalid credentials");
        if ("failed"){
            testrail.addResult(16622, "5", "This test failed", "test", "", "", "", function(body) {
                console.log(body);});
        }
        else{
            testrail.addResult(16622, "1", "This test passed", "test", "", "", "", function(body) {
                console.log(body);});
        }
    });});

If test will failed, I send fail result to TestRail, and if test will passed, I send passed results to TestRail.
But I don't know how to get failed result from expect function?
For example looks like this:
`result.status == "failed"`

**Comment by ljharb** [comment]
I'm not familiar with any test framework which allows you to get pass/fail results in this manner. It seems like you'd want a tighter mocha/testrail integration, but I'm not really sure what the best approach is.

**Comment by wuct** [comment]
Because `expect` throws an `AssertionError` when failed, you can use `try ... catch` statement:

```
try {
  expect(foo).toExist()
  console.log('passed')
} catch (e) {
  console.log('failed')
}
```

However, as @ljharb pointing out, there might be a better integration solution for TestRail.

**Comment by Alexml8456** [comment]
Thank you. I'll try.

**Comment by Alexml8456** [comment]
I was found a solution! 	
I use [jasmine reporter](http://jasmine.github.io/2.1/custom_reporter.html) it have function "result.status == "passed". Thank you for help!
