### ISSUE TITLE
Support combination of toInclude and toMatch

### ISSUE THREAD

**Issue by keirlawson** [mjackson/expect#98]
When testing redux action creators I often want to assert that there is an action in my array of actions that matches a partial object description.  From what I can see there is presently no easy way to do this with expect.

**Comment by ljharb** [comment]
`expect(array.find(x => doComparison(x))).toNotEqual(undefined)`, `expect(array.findIndex(x => doComparison(x))).toNotEqual(-1)`, something like that?

**Comment by keirlawson** [comment]
That works, though I was hoping to be able to use the built-in matching abilities of expect rather than having to write my own function

**Comment by mjackson** [comment]
@keirlawson After the next release you will be able to do stuff [like this](https://github.com/mjackson/expect/commit/866b12982c82c511977c9ce1653e01affd191840#diff-ecff5776ec07e2f531d028b8604ebc50R59)
